import type { Member } from './members.types';

export const mockMembers: Member[] = [
  {
    id: 'PAR-0001',
    lastName: 'Ouedraogo',
    firstName: 'Marie Claire',
    birthDate: '1992-04-12',
    birthPlace: 'Ouagadougou',
    gender: 'female',
    phone: '+226 70 00 00 01',
    address: 'Secteur 12, Ouagadougou',
    fatherName: 'Jean Ouedraogo',
    motherName: 'Therese Kaboré',
    maritalStatus: 'married',
    registrationDate: '2028-01-08',
    notes: 'Membre actif de la communaute paroissiale.',
  },
  {
    id: 'PAR-0002',
    lastName: 'Kaboré',
    firstName: 'Paul',
    birthDate: '1988-09-20',
    birthPlace: 'Koudougou',
    gender: 'male',
    phone: '+226 70 00 00 02',
    address: 'Quartier Tampouy, Ouagadougou',
    fatherName: 'Joseph Kaboré',
    motherName: 'Cecile Sawadogo',
    maritalStatus: 'single',
    registrationDate: '2028-01-10',
  },
  {
    id: 'PAR-0003',
    lastName: 'Sawadogo',
    firstName: 'Agnes',
    birthDate: '1976-02-05',
    birthPlace: 'Bobo-Dioulasso',
    gender: 'female',
    phone: '+226 70 00 00 03',
    address: 'Zone du Bois, Ouagadougou',
    fatherName: 'Pierre Sawadogo',
    motherName: 'Jeanne Traore',
    maritalStatus: 'widowed',
    registrationDate: '2028-01-11',
  },
];
